# Properties of rational numbers

The development of the arithmetic of rational numbers is here presupposed, but still I think it worth while to call attention to certain important matters without discussion, so as to show at the outset the standpoint assumed in what follows. I regard the whole of arithmetic as a necessary, or at least natural, consequence of the simplest arithmetic act, that of counting, and counting itself as nothing else than the successive creation of the infinite series of positive integers in which each individual is defined by the one immediately preceding; the simplest act is the passing from an already-formed individual to the consecutive new one to be formed. The chain of these numbers forms in itself an exceedingly useful instrument for the human mind; it presents an inexhaustible wealth of remarkable laws obtained by the introduction of the four fundamental operations of arithmetic. Addition is the combination of any arbitrary repetitions of the above-mentioned simplest act into a single act; from it in a similar way arises multiplication. While the performance of these two operations is always possible, that of the inverse operations, subtraction and division, proves to be limited. Whatever the immediate occasion may have been, whatever comparisons or analogies with experience, or intuition, may have led thereto; it is certainly true that just this limitation in performing the indirect operations has in each case been the real motive for a new creative act; thus negative and fractional numbers have been created by the human mind; and in the system of all rational numbers there has been gained an instrument of infinitely greater perfection. This system, which I shall denote by $R$, possesses first of all a completeness and self-containedness which I have designated in another place[^fn-1-chap-1] as characteristic of a *body of numbers* [Zahlkörper] and which consists in this that the four fundamental operations are always performable with any two individuals in $R$, i.e., the result is always an individual of $R$, the single case of division by the number zero being excepted.

For our immediate purpose, however, another property of the system $R$ is still more important; it may be expressed by saying that the system $R$ forms a well-arranged domain of one dimension extending to infinity on two opposite sides. What is meant by this is sufficiently indicated by my use of expressions borrowed from geometric ideas; but just for this reason it will be necessary to bring out clearly the corresponding purely arithmetic properties in order to avoid even the appearance as if arithmetic were in need of ideas foreign to it.

To express that the symbols $a$ and $b$ represent one and the same rational number we put $a = b$ as well as $b = a$. The fact that two rational numbers $a$, $b$ are different appears in this that the difference $a - b$ has either a positive or negative value. In the former case $a$ is said to be *greater* than $b$, $b$ *less* than $a$; this is also indicated by the symbols $a > b$, $b < a$.[^fn-2-chap-1] As in the latter case $b - a$ has a positive value it follows that $b > a$, $a < b$. In regard to these two ways in which two numbers may differ the following laws will hold:

I.  If $a > b$, and $b > c$, then $a > c$. Whenever $a$, $c$ are two different (or unequal) numbers, and $b$ is greater than the one and less than the other, we shall, without hesitation because of the suggestion of geometric ideas, express this briefly by saying: $b$ lies between the two numbers $a$, $c$.

II.  If $a$, $c$ are two different numbers, there are infinitely many different numbers lying between $a$, $c$.

III.  If $a$ is any definite number, then all numbers of the system $R$ fall into two classes, $A_1$ and $A_2$, each of which contains infinitely many individuals; the first class $A_1$ comprises all numbers $a_1$ that are $< a$, the second class $A_2$ comprises all numbers $a_2$ that are $> a$; the number $a$ itself may be assigned at pleasure to the first or second class, being respectively the greatest number of the first class or the least of the second. In every case the separation of the system $R$ into the two classes $A_1$, $A_2$ is such that every number of the first class $A_1$ is less than every number of the second class $A_2$.

[^fn-1-chap-1]: *Vorlesungen über Zahlentheorie*, by P. G. Lejeune Dirichlet. 2d ed. §159 [@lejeune_dirichlet_vorlesungen_1879].

[^fn-2-chap-1]: Hence in what follows the so-called "algebraic" greater and less are understood unless the word "absolute" is added.