# Comparison of the rational numbers with the points of a straight line

The above-mentioned properties of rational numbers recall the corresponding relations of position of the points of a straight line $L$. If the two opposite directions existing upon it are distinguished by "right" and "left," and $p$, $q$ are two different points, then either $p$ lies to the right of $q$, and at the same time $q$ to the left of $p$, or conversely $q$ lies to the right of $p$ and at the same time $p$ to the left of $q$. A third case is impossible, if $p$, $q$ are actually different points. In regard to this difference in position the following laws hold:

I.  If $p$ lies to the right of $q$, and $q$ to the right of $r$, then $p$ lies to the right of $r$; and we say that $q$ lies between the points $p$ and $r$.

II.  If $p$, $r$ are two different points, then there always exist infinitely many points that lie between $p$ and $r$.

III.  If $p$ is a definite point in $L$, then all points in $L$ fall into two classes, $P_1$, $P_2$, each of which contains infinitely many individuals; the first class $P_1$ contains all the points $p_1$, that lie to the left of $p$, and the second class $P_2$ contains all the points $p_2$ that lie to the right of $p$; the point $p$ itself may be assigned at pleasure to the first or second class. In every case the separation of the straight line $L$ into the two classes or portions $P_1$, $P_2$, is of such a character that every point of the first class $P_1$ lies to the left of every point of the second class $P_2$.

This analogy between rational numbers and the points of a straight line, as is well known, becomes a real correspondence when we select upon the straight line a definite origin or zero-point $o$ and a definite unit of length for the measurement of segments. With the aid of the latter to every rational number $a$ a corresponding length can be constructed and if we lay this off upon the straight line to the right or left of $o$ according as $a$ is positive or negative, we obtain a definite end-point $p$, which may be regarded as the point corresponding to the number $a$; to the rational number zero corresponds the point $o$. In this way to every rational number $a$, i.e., to every individual in $R$, corresponds one and only one point $p$, i.e., an individual in $L$. To the two numbers $a$, $b$ respectively correspond the two points, $p$, $q$, and if $a>b$, then $p$ lies to the right of $q$. To the laws I., II., III. of the previous Section correspond completely the laws I., II., III. of the present.