# Continuity of the straight line {#sec-continuity-of-the-straight-line}

Of the greatest importance, however, is the fact that in the straight line $L$ there are infinitely many points which correspond to no rational number. If the point $p$ corresponds to the rational number $a$, then, as is well known, the length $o\,p$ is commensurable with the invariable unit of measure used in the construction, i.e., there exists a third length, a so-called common measure, of which these two lengths are integral multiples. But the ancient Greeks already knew and had demonstrated that there are lengths incommensurable with a given unit of length, e.g., the diagonal of the square whose side is the unit of length. If we lay off such a length from the point $o$ upon the line we obtain an end-point which corresponds to no rational number. Since further it can be easily shown that there are infinitely many lengths which are incommensurable with the unit of length, we may affirm: The straight line $L$ is infinitely richer in point-individuals than the domain $R$ of rational numbers in number-individuals.

If now, as is our desire, we try to follow up arithmetically all phenomena in the straight line, the domain of rational numbers is insufficient and it becomes absolutely necessary that the instrument $R$ constructed by the creation of the rational numbers be essentially improved by the creation of new numbers such that the domain of numbers shall gain the same completeness, or as we may say at once, the same *continuity*, as the straight line.

The previous considerations are so familiar and well known to all that many will regard their repetition quite superfluous. Still I regarded this recapitulation as necessary to prepare properly for the main question. For, the way in which the irrational numbers are usually introduced is based directly upon the conception of extensive magnitudes---which itself is nowhere carefully defined---and explains number as the result of measuring such a magnitude by another of the same kind.[^fn-1-chap-3] Instead of this I demand that arithmetic shall be developed out of itself.

That such comparisons with non-arithmetic notions have furnished the immediate occasion for the extension of the number-concept may, in a general way, be granted (though this was certainly not the case in the introduction of complex numbers); but this surely is no sufficient ground for introducing these foreign notions into arithmetic, the science of numbers. Just as negative and fractional rational numbers are formed by a new creation, and as the laws of operating with these numbers must and can be reduced to the laws of operating with positive integers, so we must endeavor completely to define irrational numbers by means of the rational numbers alone. The question only remains how to do this.

The above comparison of the domain $R$ of rational numbers with a straight line has led to the recognition of the existence of gaps, of a certain incompleteness or discontinuity of the former, while we ascribe to the straight line completeness, absence of gaps, or continuity. In what then does this continuity consist? Everything must depend on the answer to this question, and only through it shall we obtain a scientific basis for the investigation of *all* continuous domains. By vague remarks upon the unbroken connection in the smallest parts obviously nothing is gained; the problem is to indicate a precise characteristic of continuity that can serve as the basis for valid deductions. For a long time I pondered over this in vain, but finally I found what I was seeking. This discovery will, perhaps, be differently estimated by different people; the majority may find its substance very commonplace. It consists of the following. In the preceding section attention was called to the fact that every point $p$ of the straight line produces a separation of the same into two portions such that every point of one portion lies to the left of every point of the other. I find the essence of continuity in the converse, i.e., in the following principle:

> "If all points of the straight line fall into two classes such that every point of the first class lies to the left of every point of the second class, then there exists one and only one point which produces this division of all points into two classes, this severing of the straight line into two portions."

As already said I think I shall not err in assuming that every one will at once grant the truth of this statement; the majority of my readers will be very much disappointed in learning that by this commonplace remark the secret of continuity is to be revealed. To this I may say that I am glad if every one finds the above principle so obvious and so in harmony with his own ideas of a line; for I am utterly unable to adduce any proof of its correctness, nor has any one the power. The assumption of this property of the line is nothing else than an axiom by which we attribute to the line its continuity, by which we find continuity in the line. If space has at all a real existence it is *not* necessary for it to be continuous; many of its properties would remain the same even were it discontinuous. And if we knew for certain that space was discontinuous there would be nothing to prevent us, in case we so desired, from filling up its gaps, in thought, and thus making it continuous; this filling up would consist in a creation of new point-individuals and would have to be effected in accordance with the above principle.

[^fn-1-chap-3]: The apparent advantage of the generality of this definition of number disappears as soon as we consider complex numbers. According to my view, on the other hand, the notion of the ratio between two numbers of the same kind can be clearly developed only after the introduction of irrational numbers.