# Creation of irrational numbers

From the last remarks it is sufficiently obvious how the discontinuous domain $R$ of rational numbers may be rendered complete so as to form a continuous domain. In Section I it was pointed out that every rational number $a$ effects a separation of the system $R$ into two classes such that every number $a_1$ of the first class $A_1$ is less than every number $a_2$ of the second class $A_2$; the number $a$ is either the greatest number of the class $A_1$ or the least number of the class $A_2$. If now any separation of the system $R$ into two classes $A_1$, $A_2$ is given which possesses only *this* characteristic property that every number $a_1$ in $A_1$ is less than every number $a_2$ in $A_2$, then for brevity we shall call such a separation a *cut* [Schnitt] and designate it by $(A_1, A_2)$. We can then say that every rational number $a$ produces one cut or, strictly speaking, two cuts, which, however, we shall not look upon as essentially different; this cut possesses, *besides*, the property that either among the numbers of the first class there exists a greatest or among the numbers of the second class a least number. And conversely, if a cut possesses this property, then it is produced by this greatest or least rational number.

But it is easy to show that there exist infinitely many cuts not produced by rational numbers. The following example suggests itself most readily.

Let $D$ be a positive integer but not the square of an integer, then there exists a positive integer $\lambda$ such that

$$
\lambda^2 < D <(\lambda + 1)^2.
$$

If we assign to the second class $A_2$, every positive rational number $a_2$ whose square is $> D$, to the first class $A_1$ all other rational numbers $a_1$, this separation forms a cut $(A_1, A_2)$, i.e., every number $a_1$ is less than every number $a_2$. For if $a_1 = 0$, or is negative, then on that ground $a_1$ is less than any number $a_2$, because, by definition, this last is positive; if $a_1$ is positive, then is its square $\leqq D$, and hence $a_1$ is less than any positive number $a_2$ whose square is $> D$.

But this cut is produced by no rational number. To demonstrate this it must be shown first of all that there exists no rational number whose square $= D$. Although this is known from the first elements of the theory of numbers, still the following indirect proof may find place here. If there exist a rational number whose square $= D$, then there exist two positive integers $t$, $u$, that satisfy the equation
$$
t^2 - Du^2 = 0,
$$
and we may assume that $u$ is the *least* positive integer possessing the property that its square, by multiplication by $D$, may be converted into the square of an integer $t$. Since evidently
$$
\lambda u < t < (\lambda + 1) u,
$$
the number $u' = t - \lambda u$ is a positive integer certainly *less* than $u$. If further we put
$$
t' = Du - \lambda t,
$$
$t'$ is likewise a positive integer, and we have
$$
t'^2 - Du'^2 = (\lambda^2 - D)(t^2 - Du^2) = 0,
$$
which is contrary to the assumption respecting $u$.

Hence the square of every rational number $x$ is either $< D$ or $> D$. From this it easily follows that there is neither in the class $A_1$ a greatest, nor in the class $A_2$ a least number. For if we put
$$
y = \frac{x(x^2 + 3D)}{3x^2 + D},
$$
we have

$$
y - x = \frac{2x(D - x^2)}{3x^2 + D}
$$

and

$$
y^2 - D = \frac{(x^2 - D)^3}{(3x^2 + D)^2}.
$$

If in this we assume $x$ to be a positive number from the class $A_1$, then $x^2<D$, and hence $y>x$ and $y^2<D$. Therefore $y$ likewise belongs to the class $A_1$. But if we assume $x$ to be a number from the class $A_2$, then $x^2>D$, and hence $y<x$, $y>0$, and $y^2>D$. Therefore $y$ likewise belongs to the class $A_2$. This cut is therefore produced by no rational number.

In this property that not all cuts are produced by rational numbers consists the incompleteness or discontinuity of the domain $R$ of all rational numbers.

Whenever, then, we have to do with a cut $(A_1, A_2)$ produced by no rational number, we create a new, an *irrational* number $\alpha$, which we regard as completely defined by this cut $(A_1, A_2)$; we shall say that the number $\alpha$ corresponds to this cut, or that it produces this cut. From now on, therefore, to every definite cut there corresponds a definite rational or irrational number, and we regard two numbers as *different* or *unequal* always and only when they correspond to essentially different cuts.

In order to obtain a basis for the orderly arrangement of all *real*, i.e., of all rational and irrational numbers we must investigate the relation between any two cuts $(A_1, A_2)$ and $(B_1, B_2)$ produced by any two numbers $\alpha$ and $\beta$. Obviously a cut $(A_1, A_2)$ is given completely when one of the two classes, e.g., the first $A_1$ is known, because the second $A_2$ consists of all rational numbers not contained in $A_1$, and the characteristic property of such a first class lies in this that if the number $a_1$ is contained in it, it also contains all numbers less than $a_1$. If now we compare two such first classes $A_1$, $B_1$ with each other, it may happen

1\. That they are perfectly identical, i.e., that every number contained in $A_1$ is also contained in $B_1$, and that every number contained in $B_1$ is also contained in $A_1$. In this case $A_2$ is necessarily identical with $B_2$, and the two cuts are perfectly identical, which we denote in symbols by $\alpha=\beta$ or $\beta=\alpha$.

But if the two classes $A_1$, $B_1$ are not identical, then there exists in the one, e.g., in $A_1$, a number $a'_1=b'_2$ not contained in the other $B_1$ and consequently found in $B_2$; hence all numbers $b_1$ contained in $B_1$ are certainly less than this number $a'_1=b'_2$ and therefore all numbers $b_1$ are contained in $A_1$.

2\. If now this number $a'_1$ is the only one in $A_1$ that is not contained in $B_1$, then is every other number $a_1$ contained in $A_1$ also contained in $B_1$ and is consequently $<a'_1$, i.e., $a'_1$ is the greatest among all the numbers $a_1$, hence the cut $(A_1, A_2)$ is produced by the rational number $a=a'_1=b'_2$. Concerning the other cut $(B_1, B_2)$ we know already that all numbers $b_1$ in $B_1$ are also contained in $A_1$ and are less than the number $a'_1=b'_2$ which is contained in $B_2$; every other number $b_2$ contained in $B_2$ must, however, be greater than $b'_2$, for otherwise it would be less than $a'_1$, therefore contained in $A_1$ and hence in $B_1$; hence $b'_2$ is the least among all numbers contained in $B_2$, and consequently the cut $(B_1, B_2)$ is produced by the same rational number $\beta = b'_2 = a'_1 = \alpha$. The two cuts are then only unessentially different.

3\. If, however, there exist in $A_1$ at least two different numbers $a'_1 = b'_2$ and $a''_1 = b''_2$, which are not contained in $B_1$, then there exist infinitely many of them, because all the infinitely many numbers lying between $a'_1$ and $a''_1$ are obviously contained in $A_1$ (Section I, II.) but not in $B_1$. In this case we say that the numbers $\alpha$ and $\beta$ corresponding to these two essentially different cuts $(A_1, A_2)$ and $(B_1, B_2)$ are *different*, and further that $\alpha$ is *greater* than $\beta$, that $\beta$ is *less* than $\alpha$, which we express in symbols by $\alpha > \beta$ as well as $\beta < \alpha$. It is to be noticed that this definition coincides completely with the one given earlier, when $\alpha$, $\beta$ are rational.

The remaining possible cases are these:

4\. If there exists in $B_1$ one and only one number $b'_1 = a'_2$, that is not contained in $A_1$ then the two cuts $(A_1, A_2)$ and $(B_1, B_2)$ are only unessentially different and they are produced by one and the same rational number $\alpha = a'_2 = b'_1 = \beta$.

5\. But if there are in $B_1$ at least two numbers which are not contained in $A_1$, then $\beta > \alpha$, $\alpha < \beta$.

As this exhausts the possible cases, it follows that of two different numbers one is necessarily the greater, the other the less, which gives two possibilities. A third case is impossible. This was indeed involved in the use of the *comparative* (greater, less) to designate the relation between $\alpha$, $\beta$; but this use has only now been justified. In just such investigations one needs to exercise the greatest care so that even with the best intention to be honest he shall not, through a hasty choice of expressions borrowed from other notions already developed, allow himself to be led into the use of inadmissible transfers from one domain to the other.

If now we consider again somewhat carefully the case $\alpha>\beta$ it is obvious that the less number $\beta$, if rational, certainly belongs to the class $A_1$; for since there is in $A_1$ a number $a'_1=b'_2$ which belongs to the class $B_2$, it follows that the number $\beta$, whether the greatest number in $B_1$ or the least in $B_2$ is certainly $\leqq a'_1$ and hence contained in $A_1$. Likewise it is obvious from $\alpha>\beta$ that the greater number $\alpha$, if rational, certainly belongs to the class $B_2$, because $\alpha \geqq a'_1$. Combining these two considerations we get the following result: If a cut is produced by the number $\alpha$ then any rational number belongs to the class $A_1$ or to the class $A_2$ according as it is less or greater than $\alpha$; if the number $\alpha$ is itself rational it may belong to either class.

From this we obtain finally the following: If $\alpha>\beta$, i.e., if there are infinitely many numbers in $A_1$ not contained in $B_1$ then there are infinitely many such numbers that at the same time are different from $\alpha$ and from $\beta$; every such rational number $c$ is $<\alpha$, because it is contained in $A_1$ and at the same time it is $>\beta$ because contained in $B_2$.