# Continuity of the domain of real Numbers

In consequence of the distinctions just established the system $\mathfrak{R}$ of all real numbers forms a well-arranged domain of one dimension; this is to mean merely that the following laws prevail:

I\. If $\alpha>\beta$, and $\beta>\gamma$, then is also $\alpha>\gamma$. We shall say that the number $\beta$ lies between $\alpha$ and $\gamma$.

II\. If $\alpha$, $\gamma$ are any two different numbers, then there exist infinitely many different numbers $\beta$ lying between $\alpha$, $\gamma$.

III\. If $\alpha$ is any definite number then all numbers of the system $\mathfrak{R}$ fall into two classes $\mathfrak{A}_1$ and $\mathfrak{A}_2$ each of which contains infinitely many individuals; the first class $\mathfrak{A}_1$ comprises all the numbers $\alpha_1$ that are less than $\alpha$, the second $\mathfrak{A}_2$ comprises all the numbers $\alpha_2$ that are greater than $\alpha$; the number $\alpha$ itself may be assigned at pleasure to the first class or to the second, and it is respectively the greatest of the first or the least of the second class. In each case the separation of the system $\mathfrak{R}$ into the two classes $\mathfrak{A}_1$, $\mathfrak{A}_2$ is such that every number of first class $\mathfrak{A}_1$ is smaller than every number of the second class $\mathfrak{A}_2$ and we say that this separation is produced by the number $\alpha$.

For brevity and in order not to weary the reader I suppress the proofs of these theorems which follow immediately from the definitions of the previous section.

Beside these properties, however, the domain $\mathfrak{R}$ possesses also *continuity*; i.e., the following theorem is true:

IV\. If the system $\mathfrak{R}$ of all real numbers breaks up into two classes $\mathfrak{A}_1$, $\mathfrak{A}_2$ such that every number $\alpha_1$ of the class $\mathfrak{A}_1$ is less than every number $\alpha_2$ of the class $\mathfrak{A}_2$ then there exists one and only one number $\alpha$ by which this separation is produced.

::: {.proof}
By the separation or the cut of $\mathfrak{R}$ into $\mathfrak{A}_1$ and $\mathfrak{A}_2$ we obtain at the same time a cut $(A_1, A_2)$ of the system $R$ of all rational numbers which is defined by this that $A_1$ contains all rational numbers of the class $\mathfrak{A}_1$ and $A_2$ all other rational numbers, i.e., all rational numbers of the class $\mathfrak{A}_2$. Let $\alpha$ be the perfectly definite number which produces this cut $(A_1, A_2)$. If $\beta$ is any number different from $\alpha$, there are always infinitely many rational numbers $c$ lying between $\alpha$ and $\beta$. If $\beta<\alpha$, then $c<\alpha$; hence $c$ belongs to the class $A_1$ and consequently also to the class $\mathfrak{A}_1$, and since at the same time $\beta<c$ then $\beta$ also belongs to the same class $\mathfrak{A}_1$, because every number in $\mathfrak{A}_2$ is greater than every number $c$ in $\mathfrak{A}_1$. But if $\beta>\alpha$, then is $c>\alpha$; hence $c$ belongs to the class $A_2$ and consequently also to the class $\mathfrak{A}_2$, and since at the same time $\beta>c$, then $\beta$ also belongs to the same class $\mathfrak{A}_2$, because every number in $\mathfrak{A}_1$ is less than every number $c$ in $\mathfrak{A}_2$. Hence every number $\beta$ different from $\alpha$ belongs to the class $\mathfrak{A}_1$ or to the class $\mathfrak{A}_2$ according as $\beta<\alpha$ or $\beta>\alpha$; consequently $\alpha$ itself is either the greatest number in $\mathfrak{A}_1$ or the least number in $\mathfrak{A}_2$, i.e., $\alpha$ is one and obviously the only number by which the separation of $R$ into the classes $\mathfrak{A}_1$, $\mathfrak{A}_2$ is produced. Which was to be proved.
:::