## Operations with real numbers

To reduce any operation with two real numbers $\alpha$, $\beta$ to operations with rational numbers, it is only necessary from the cuts $(A_1, A_2)$, $(B_1, B_2)$ produced by the numbers $\alpha$ and $\beta$ in the system $R$ to define the cut $(C_1, C_2)$ which is to correspond to the result of the operation, $\gamma$. I confine myself here to the discussion of the simplest case, that of addition.

If $c$ is any rational number, we put it into the class $C_1$, provided there are two numbers one $a_1$ in $A_1$ and one $b_1$ in $B_1$ such that their sum $a_1+b_1 \geqq c$; all other rational numbers shall be put into the class $C_2$. This separation of all rational numbers into the two classes $C_1$, $C_2$ evidently forms a cut, since every number $c_1$ in $C_1$ is less than every number $c_2$ in $C_2$. If both $\alpha$ and $\beta$ are rational, then every number $c_1$ contained in $C_1$ is $\leqq\alpha+\beta$, because $a_1\leqq\alpha$, $b_1\leqq\beta$, and therefore $a_1+b_1 \leqq\alpha+\beta$; further, if there were contained in $C_2$ a number $c_2<\alpha+\beta$, hence $\alpha+\beta=c_2+p$, where $p$ is a positive rational number, then we should have

$$
c_2=(\alpha- \frac{1}{2} p)+(\beta- \frac{1}{2} p),
$$

which contradicts the definition of the number $c_2$, because $\alpha- \frac{1}{2} p$ is a number in $A_1$, and $\beta- \frac{1}{2} p$ a number in $B_1$; consequently every number $c_2$ contained in $C_2$ is $\geqq\alpha+\beta$. Therefore in this case the cut $(C_1, C_2)$ is produced by the sum $\alpha+\beta$. Thus we shall not violate the definition which holds in the arithmetic of rational numbers if in all cases we understand by the sum $\alpha+\beta$ of any two real numbers $\alpha$, $\beta$ that number $\gamma$ by which the cut $(C_1, C_2)$ is produced. Further, if only one of the two numbers $\alpha$, $\beta$ is rational, e.g., $\alpha$, it is easy to see that it makes no difference with the sum $\gamma=\alpha+\beta$ whether the number $\alpha$ is put into the class $A_1$ or into the class $A_2$.

Just as addition is defined, so can the other operations of the so-called elementary arithmetic be defined, viz., the formation of differences, products, quotients, powers, roots, logarithms, and in this way we arrive at real proofs of theorems (as, e.g., $\sqrt{2}\cdot\sqrt{3} =\sqrt{6}$), which to the best of my knowledge have never been established before. The excessive length that is to be feared in the definitions of the more complicated operations is partly inherent in the nature of the subject but can for the most part be avoided. Very useful in this connection is the notion of an *interval*, i.e., a system $A$ of rational numbers possessing the following characteristic property: if $a$ and $a'$ are numbers of the system $A$, then are all rational numbers lying between $a$ and $a'$ contained in $A$. The system $R$ of all rational numbers, and also the two classes of any cut are intervals. If there exist a rational number $a_1$ which is less and a rational number $a_2$ which is greater than every number of the interval $A$, then $A$ is called a finite interval; there then exist infinitely many numbers in the same condition as $a_1$ and infinitely many in the same condition as $a_2$; the whole domain $R$ breaks up into three parts $A_1$, $A$, $A_2$ and there enter two perfectly definite rational or irrational numbers $\alpha_1$, $\alpha_2$ which may be called respectively the lower and upper (or the less and greater) *limits* of the interval; the lower limit $\alpha_1$ is determined by the cut for which the system $A_1$ forms the first class and the upper $\alpha_2$ by the cut for which the system $A_2$ forms the second class. Of every rational or irrational number $\alpha$ lying between $\alpha_1$ and $\alpha_2$ it may be said that it lies *within* the interval $A$. If all numbers of an interval $A$ are also numbers of an interval $B$, then $A$ is called a portion of $B$.

Still lengthier considerations seem to loom up when we attempt to adapt the numerous theorems of the arithmetic of rational numbers (as, e.g., the theorem $(a+b)c=ac+bc$) to any real numbers. This, however, is not the case. It is easy to see that it all reduces to showing that the arithmetic operations possess a certain continuity. What I mean by this statement may be expressed in the form of a general theorem:

> "If the number $\lambda$ is the result of an operation performed on the numbers $\alpha$, $\beta$, $\gamma$, $\ldots$ and $\lambda$ lies within the interval $L$, then intervals $A$, $B$, $C$, ... can be taken within which lie the numbers $\alpha$, $\beta$, $\gamma$, $\ldots$ such that the result of the same operation in which the numbers $\alpha$, $\beta$, $\gamma$, $\ldots$ are replaced by arbitrary numbers of the intervals $A$, $B$, C, ... is always a number lying within the interval $L$."

The forbidding clumsiness, however, which marks the statement of such a theorem convinces us that something must be brought in as an aid to expression; this is, in fact, attained in the most satisfactory way by introducing the ideas of *variable magnitudes*, *functions*, *limiting values*, and it would be best to base the definitions of even the simplest arithmetic operations upon these ideas, a matter which, however, cannot be carried further here.