# The nature and meaning of numbers

## Preface to the first edition

In science nothing capable of proof ought to be accepted without proof. Though this demand seems so reasonable yet I cannot regard it as having been met even in the most recent methods of laying the foundations of the simplest science; viz., that part of logic which deals with the theory of numbers.[^fn-1-prefaces-part-2] In speaking of arithmetic (algebra, analysis) as a part of logic I mean to imply that I consider the number-concept entirely independent of the notions or intuitions of space and time, that I consider it an immediate result from the laws of thought. My answer to the problems propounded in the title of this paper is, then, briefly this: numbers are free creations of the human mind; they serve as a means of apprehending more easily and more sharply the difference of things. It is only through the purely logical process of building up the science of numbers and by thus acquiring the continuous number-domain that we are prepared accurately to investigate our notions of space and time by bringing them into relation with this number-domain created in our mind.[^fn-2-prefaces-part-2] If we scrutinise closely what is done in counting an aggregate or number of things, we are led to consider the ability of the mind to relate things to things, to let a thing correspond to a thing, or to represent a thing by a thing, an ability without which no thinking is possible. Upon this unique and therefore absolutely indispensable foundation, as I have already affirmed in an announcement of this paper,[^fn-3-prefaces-part-2] must, in my judgment, the whole science of numbers be established. The design of such a presentation I had formed before the publication of my paper on *Continuity*, but only after its appearance and with many interruptions occasioned by increased official duties and other necessary labors, was I able in the years 1872 to 1878 to commit to paper a first rough draft which several mathematicians examined and partially discussed with me. It bears the same title and contains, though not arranged in the best order, all the essential fundamental ideas of my present paper, in which they are more carefully elaborated. As such main points I mention here the sharp distinction between finite and infinite [(64)](2_05_the-finite-and-infinite.qmd#par-64), the notion of the number [*Anzahl*] of things [(161)](2_14_number-of-the-elements-of-a-finite-system.qmd#par-161), the proof that the form of argument known as complete induction (or the inference from $n$ to $n + 1$) is really conclusive [(59)](2_04_transformation-of-a-system-in-itself.qmd#par-59), [(60)](2_04_transformation-of-a-system-in-itself.qmd#par-60), [(80)](2_06_simply-infinite-systems.qmd#par-80), and that therefore the definition by induction (or recursion) is determinate and consistent [(126)](2_09_definition-of-a-transformation-of-the-number-series-by-induction.qmd#par-126).

This memoir can be understood by any one possessing what is usually called good common sense; no technical philosophic, or mathematical, knowledge is in the least degree required. But I feel conscious that many a reader will scarcely recognise in the shadowy forms which I bring before him his numbers which all his life long have accompanied him as faithful and familiar friends; he will be frightened by the long series of simple inferences corresponding to our step-by-step understanding, by the matter-of-fact dissection of the chains of reasoning on which the laws of numbers depend, and will become impatient at being compelled to follow out proofs for truths which to his supposed inner consciousness seem at once evident and certain. On the contrary in just this possibility of reducing such truths to others more simple, no matter how long and apparently artificial the series of inferences, I recognise a convincing proof that their possession or belief in them is never given by inner consciousness but is always gained only by a more or less complete repetition of the individual inferences. I like to compare this action of thought, so difficult to trace on account of the rapidity of its performance, with the action which an accomplished reader performs in reading; this reading always remains a more or less complete repetition of the individual steps which the beginner has to take in his wearisome spelling-out; a very small part of the same, and therefore a very small effort or exertion of the mind, is sufficient for the practised reader to recognise the correct, true word, only with very great probability, to be sure; for, as is well known, it occasionally happens that even the most practised proof-reader allows a typographical error to escape him, i.e., reads falsely, a thing which would be impossible if the chain of thoughts associated with spelling were fully repeated. So from the time of birth, continually and in increasing measure we are led to relate things to things and thus to use that faculty of the mind on which the creation of numbers depends; by this practice continually occurring, though without definite purpose, in our earliest years and by the attending formation of judgments and chains of reasoning we acquire a store of real arithmetic truths to which our first teachers later refer as to something simple, self-evident, given in the inner consciousness; and so it happens that many very complicated notions (as for example that of the number [*Anzahl*] of things) are erroneously regarded as simple. In this sense which I wish to express by the word formed after a well-known saying *`\greekfont ἀεί ὁ ἄνθρωπος ἀριθμητίζει`{=latex}`ἀεί ὁ ἄνθρωπος ἀριθμητίζει`{=html}*, I hope that the following pages, as an attempt to establish the science of numbers upon a uniform foundation will find a generous welcome and that other mathematicians will be led to reduce the long series of inferences to more moderate and attractive proportions.

In accordance with the purpose of this memoir I restrict myself to the consideration of the series of so-called natural numbers. In what way the gradual extension of the number-concept, the creation of zero, negative, fractional, irrational and complex numbers are to be accomplished by reduction to the earlier notions and that without any introduction of foreign conceptions (such as that of measurable magnitudes, which according to my view can attain perfect clearness only through the science of numbers), this I have shown at least for irrational numbers in my former memoir on *Continuity* (1872) [@dedekind_stetigkeit_1872]; in a way wholly similar, as I have already shown in Section III. of that memoir,[^fn-4-prefaces-part-2] may the other extensions be treated, and I propose sometime to present this whole subject in systematic form. From just this point of view it appears as something self-evident and not new that every theorem of algebra and higher analysis, no matter how remote, can be expressed as a theorem about natural numbers,---a declaration I have heard repeatedly from the lips of Dirichlet. But I see nothing meritorious--and this was just as far from Dirichlet's thought---in actually performing this wearisome circumlocution and insisting on the use and recognition of no other than rational numbers. On the contrary, the greatest and most fruitful advances in mathematics and other sciences have invariably been made by the creation and introduction of new concepts, rendered necessary by the frequent recurrence of complex phenomena which could be controlled by the old notions only with difficulty. On this subject I gave a lecture before the philosophic faculty in the summer of 1854 on the occasion of my admission as privat-docent in Göttingen. The scope of this lecture met with the approval of Gauss; but this is not the place to go into further detail.

Instead of this I will use the opportunity to make some remarks relating to my earlier work, mentioned above, on *Continuity and Irrational Numbers*. The theory of irrational numbers there presented, wrought out in the fall of 1853, is based on the phenomenon (Section IV.)[^fn-5-prefaces-part-2] occurring in the domain of rational numbers which I designate by the term cut [*Schnitt*] and which I was the first to investigate carefully; it culminates in the proof of the continuity of the new domain of real numbers (Section V., IV.).[^fn-6-prefaces-part-2] It appears to me to be somewhat simpler, I might say easier, than the two theories, different from it and from each other, which have been proposed by Weierstrass and G. Cantor, and which likewise are perfectly rigorous. It has since been adopted without essential modification by U. Dini in his *Fondamenti per la teorica delle funzioni di variabili reali* (Pisa, 1878) [@dini_fondamenti_1878]; but the fact that in the course of this exposition my name happens to be mentioned, not in the description of the purely arithmetic phenomenon of the cut but when the author discusses the existence of a measurable quantity corresponding to the cut, might easily lead to the supposition that my theory rests upon the consideration of such quantities. Nothing could be further from the truth; rather have I in Section III.[^fn-7-prefaces-part-2] of my paper advanced several reasons why I wholly reject the introduction of measurable quantities; indeed, at the end of the paper I have pointed out with respect to their existence that for a great part of the science of space the continuity of its configurations is not even a necessary condition, quite aside from the fact that in works on geometry arithmetic is only casually mentioned by name but is never clearly defined and therefore cannot be employed in demonstrations. To explain this matter more clearly I note the following example: If we select three non-collinear points $A$, $B$, $C$ at pleasure, with the single limitation that the ratios of the distances $AB$, $AC$, $BC$ are algebraic numbers,[^fn-8-prefaces-part-2] and regard as existing in space only those points $M$, for which the ratios of $AM$, $BM$, $CM$ to $AB$ are likewise algebraic numbers, then is the space made up of the points $M$, as is easy to see, everywhere discontinuous; but in spite of this discontinuity, and despite the existence of gaps in this space, all constructions that occur in Euclid's *Elements*, can, so far as I can see, be just as accurately effected as in perfectly continuous space; the discontinuity of this space would not be noticed in Euclid's science, would not be felt at all. If any one should say that we cannot conceive of space as anything else than continuous, I should venture to doubt it and to call attention to the fact that a far advanced, refined scientific training is demanded in order to perceive clearly the essence of continuity and to comprehend that besides rational quantitative relations, also irrational, and besides algebraic, also transcendental quantitative relations are conceivable. All the more beautiful it appears to me that without any notion of measurable quantities and simply by a finite system of simple thought-steps man can advance to the creation of the pure continuous number-domain; and only by this means in my view is it possible for him to render the notion of continuous space clear and definite.

The same theory of irrational numbers founded upon the phenomenon of the cut is set forth in the *Introduction à la théorie des fonctions d'une variable* by J. Tannery (Paris, 1886) [@tannery_introduction_1886]. If I rightly understand a passage in the preface to this work, the author has thought out his theory independently, that is, at a time when not only my paper, but Dini's *Fondamenti* mentioned in the same preface, was unknown to him. This agreement seems to me a gratifying proof that my conception conforms to the nature of the case, a fact recognised by other mathematicians, e.g., by Pasch in his *Einleitung in die Differential- und Integralrechnung* (Leipzig, 1883) [@pasch_einleitung_1882]. But I cannot quite agree with Tannery when he calls this theory the development of an idea due to J. Bertrand and contained in his *Traité d'arithmétique* [@bertrand_traite_1885], consisting in this that an irrational number is defined by the specification of all rational numbers that are less and all those that are greater than the number to be defined. As regards this statement which is repeated by Stolz---apparently without careful investigation---in the preface to the second part of his *Vorlesungen über allgemeine Arithmetik* (Leipzig, 1886) [@stolz_vorlesungen_1886], I venture to remark the following: That an irrational number is to be considered as fully defined by the specification just described, this conviction certainly long before the time of Bertrand was the common property of all mathematicians who concerned themselves with the notion of the irrational. Just this manner of determining it is in the mind of every computer who calculates the irrational root of an equation by approximation, and if, as Bertrand does exclusively in his book, (the eighth edition, of the year 1885, lies before me,) one regards the irrational number as the ratio of two measurable quantities, then is this manner of determining it already set forth in the clearest possible way in the celebrated definition which Euclid gives of the equality of two ratios (*Elements*, V., 5). This same most ancient conviction has been the source of my theory as well as that of Bertrand and many other more or less complete attempts to lay the foundations for the introduction of irrational numbers into arithmetic. But though one is so far in perfect agreement with Tannery, yet in an actual examination he cannot fail to observe that Bertrand's presentation, in which the phenomenon of the cut in its logical purity is not even mentioned, has no similarity whatever to mine, inasmuch as it resorts at once to the existence of a measurable quantity, a notion which for reasons mentioned above I wholly reject. Aside from this fact this method of presentation seems also in the succeeding definitions and proofs, which are based on the postulate of this existence, to present gaps so essential that I still regard the statement made in my paper (Section VI.),[^fn-9-prefaces-part-2] that the theorem $\sqrt{2}\cdot\sqrt{3}=\sqrt{6}$ has nowhere yet been strictly demonstrated, as justified with respect to this work also, so excellent in many other regards and with which I was unacquainted at that time.

::: {.flushright latex="" custom-style="flushright"}
R. Dedekind.
:::

[Harzburg]{.smallcaps}, October 5, 1887.

[^fn-1-prefaces-part-2]: Of the works which have come under my observation I mention the valuable *Lehrbuch der Arithmetik und Algebra* of E. Schröder (Leipzig, 1873) [@schroder_lehrbuch_1873], which contains a bibliography of the subject, and in addition the memoirs of Kronecker and von Helmholtz upon the Number-Concept and upon Counting and Measuring (in the collection of philosophical essays published in honor of E. Zeller, Leipzig, 1887) [@zeller_philosophische_1887]. The appearance of these memoirs has induced me to publish my own views, in many respects similar but in foundation essentially different, which I formulated many years ago in absolute independence of the works of others.

[^fn-2-prefaces-part-2]: See Section III of my memoir, *Continuity and Irrational Numbers* (Braunschweig, 1872) [@dedekind_stetigkeit_1872] translated at @sec-continuity-of-the-straight-line of the present volume.

[^fn-3-prefaces-part-2]: Dirichlet's *Vorlesungen über Zahlentheorie*, third edition, 1879, § 163, note on page 470 [@lejeune_dirichlet_vorlesungen_1879].

[^fn-4-prefaces-part-2]: @sec-continuity-of-the-straight-line of the present volume.

[^fn-5-prefaces-part-2]: @sec-creation-of-irrational-numbers of the present volume.

[^fn-6-prefaces-part-2]: [@sec-continuity-of-the-domain-of-real-numbers, IV](1_05_continuity-of-the-domain-of-real-numbers.qmd#par-7-continuity-of-the-domain-of-real-numbers) of the present volume.

[^fn-7-prefaces-part-2]: @sec-continuity-of-the-straight-line of the present volume.

[^fn-8-prefaces-part-2]: Dirichlet's *Vorlesungen über Zahlentheorie*, § 159 of the second edition, § 160 of the third [@lejeune_dirichlet_vorlesungen_1879].

[^fn-9-prefaces-part-2]: @sec-operations-with-real-numbers of this volume.

## Preface to the second edition

The present memoir soon after its appearance met with both favorable and unfavorable criticisms; indeed serious faults were charged against it. I have been unable to convince myself of the justice of these charges, and I now issue a new edition of the memoir, which for some time has been out of print, without change, adding only the following notes to the first preface.

The property which I have employed as the definition of the infinite system had been pointed out before the appearance of my paper by G. Cantor (*Ein Beitrag zur Mannigfaltigkeitslehre*, *Crelle's Journal*, Vol. 84, 1878) [@cantor_beitrag_1878], as also by Bolzano (*Paradoxien des Unendlichen*, § 20, 1851) [@bolzano_paradoxien_1851]. But neither of these authors made the attempt to use this property for the definition of the infinite and upon this foundation to establish with rigorous logic the science of numbers, and just in this consists the content of my wearisome labor which in all its essentials I had completed several years before the appearance of Cantor's memoir and at a time when the work of Bolzano was unknown to me even by name. For the benefit of those who are interested in and understand the difficulties of such an investigation, I add the following remark. We can lay down an entirely different definition of the finite and infinite, which appears still simpler since the notion of similarity of transformation is not even assumed, viz.:

> A system $S$ is said to be finite when it may be so transformed in itself [(36)](2_04_transformation-of-a-system-in-itself.qmd#par-36) that no proper part [(6)](2_01_systems-of-elements.qmd#par-6) of $S$ is transformed in itself; in the contrary case $S$ is called an infinite system.

Now let us attempt to erect our edifice upon this new foundation! We shall soon meet with serious difficulties, and I believe myself warranted in saying that the proof of the perfect agreement of this definition with the former can be obtained only (and then easily) when we are permitted to assume the series of natural numbers as already developed and to make use of the final considerations in [(131)](2_09_definition-of-a-transformation-of-the-number-series-by-induction.qmd#par-131); and yet nothing is said of all these things in either the one definition or the other! From this we can see how very great is the number of steps in thought needed for such a remodeling of a definition.

About a year after the publication of my memoir I became acquainted with G. Frege's *Grundlagen der Arithmetik* [@frege_grundlagen_1884], which had already appeared in the year 1884. However different the view of the essence of number adopted in that work is from my own, yet it contains, particularly from § 79 on, points of very close contact with my paper, especially with my definition [(44)](2_04_transformation-of-a-system-in-itself.qmd#par-44). The agreement, to be sure, is not easy to discover on account of the different form of expression; but the positiveness with which the author speaks of the logical inference from $n$ to $n+1$ ([@frege_grundlagen_1884, p. 93], below) shows plainly that here he stands upon the same ground with me. In the meantime E. Schröder's *Vorlesungen über die Algebra der Logik* [@schroder_vorlesungen_1891] has been almost completed (1890--1891). Upon the importance of this extremely suggestive work, to which I pay my highest tribute, it is impossible here to enter further; I will simply confess that in spite of the remark made on p. 253 of Part I., I have retained my somewhat clumsy symbols [(8)](2_01_systems-of-elements.qmd#par-8) and [(17)](2_01_systems-of-elements.qmd#par-17); they make no claim to be adopted generally but are intended simply to serve the purpose of this arithmetic paper to which in my view they are better adapted than sum and product symbols.

::: {.flushright latex="" custom-style="flushright"}
R. Dedekind.
:::

[Harzburg]{.smallcaps}, August 24, 1893.
