# Addition of numbers {#sec-addition-of-numbers}

[**135.**]{#par-135} Definition. It is natural to apply the definition set forth in theorem [(126)](2_09_definition-of-a-transformation-of-the-number-series-by-induction.qmd#par-126) of a transformation $\psi$ of the number-series $N$, or of the *function* $\psi(n)$ determined by it to the case, where the system there denoted by $\Omega$ in which the transform $\psi(N)$ is to be contained, is the number-series $N$ itself, because for this system $\Omega$ a transformation $\theta$ of $\Omega$ in itself already exists, viz., that transformation $\phi$ by which $N$ is set in order as a simply infinite system [(71)](2_06_simply-infinite-systems.qmd#par-71), [(73)](2_06_simply-infinite-systems.qmd#par-73). Then is also $\Omega=N$, $\theta(n)=\phi(n)=n'$, hence

$$
\mathrm{I.\ }\psi(N) \partof N,
$$

and it remains in order to determine $\psi$ completely only to select the element $\omega$ from $\Omega$, i.e., from $N$, at pleasure. If we take $\omega=1$, then evidently $\psi$ becomes the identical transformation [(21)](2_02_transformation-of-a-system.qmd#par-21) of $N$, because the conditions

[
$$
\psi(1)=1,\quad \psi(n')=(\psi(n))'
$$
]{#equ-par-135-I}

are generally satisfied by $\psi(n)=n$. If then we are to produce another transformation $\psi$ of $N$, then for $\omega$ we must select a number $m'$ different from 1, by [(78)](2_06_simply-infinite-systems.qmd#par-78) contained in $N$, where $m$ itself denotes any number; since the transformation $\psi$ is obviously dependent upon the choice of this number $m$, we denote the corresponding transform $\psi(n)$ of an arbitrary number $n$ by the symbol $m+n$, and call this number the *sum* which arises from the number $m$ by the *addition* of the number $n$, or in short the sum of the numbers $m$, $n$. Therefore by [(126)](2_09_definition-of-a-transformation-of-the-number-series-by-induction.qmd#par-126) this sum is completely determined by the conditions[^fn-1-chap-18]

[
$$
\text{II. } m+1=m',
$$
]{#equ-par-135-II}

[
$$
\text{III. } m+n'=(m+n)'.
$$
]{#equ-par-135-III}

[**136.**]{#par-136} Theorem. $m'+n=m+n'$.

Proof by complete induction [(80)](2_06_simply-infinite-systems.qmd#par-80). For

$\rho$. the theorem is true for $n=1$, since by ([(135), II](#equ-par-135-II))

$$
m'+1=(m')'=(m+1)',
$$

and by [(135, III)](#equ-par-135-III) $(m+1)'=m+1'$.

$\sigma$. If the theorem is true for a number $n$, and we put the following number $n'=p$ then is $m'+n=m+p$, hence also $(m'+n)'=(m+p)'$, whence by [(135, III)](#equ-par-135-III) $m'+p=m+p'$; therefore the theorem is true also for the following number $p$, which was to be proved.

[**137.**]{#par-137} Theorem. $m'+n=(m+n)'$.

The proof follows from [(136)](#par-136) and [(135, III)](#equ-par-135-III).

[**138.**]{#par-138} Theorem. $1+n=n'$.

Proof by complete induction [(80)](2_06_simply-infinite-systems.qmd#par-80). For

$\rho$. by [(135, II)](#equ-par-135-II) the theorem is true for $n=1$.

$\sigma$. If the theorem is true for a number $n$ and we put $n'=p$, then $1+n=p$, therefore also $(1+n)'=p'$, whence by [(135, III)](#equ-par-135-III) $1+p=p'$, i.e., the theorem is true also for the following number $p$, which was to be proved.

[**139.**]{#par-139} Theorem. $1+n=n+1$.

The proof follows from [(138)](#par-138) and [(135, II)](#equ-par-135-II).

[**140.**]{#par-140} Theorem. $m+n=n+m$.

Proof by complete induction [(80)](2_06_simply-infinite-systems.qmd#par-80). For

$\rho$. by [(139)](#par-139) the theorem is true for $n=1$.

$\sigma$. If the theorem is true for a number $n$, then there follows also $(m+n)'=(n+m)'$, i.e., by [(135, III)](#equ-par-135-III) $m+n'=n+m'$, hence by [(136)](#par-136) $m+n'=n'+m$; therefore the theorem is also true for the following number $n'$, which was to be proved.

[**141.**]{#par-141} Theorem. $(l+m)+n=l+(m+n)$.

Proof by complete induction [(80)](2_06_simply-infinite-systems.qmd#par-80). For

$\rho$. the theorem is true for $n=1$, because by ([135, II](#equ-par-135-II), [III](#equ-par-135-III), [II](#equ-par-135-II)) $(l+m)+1=(l+m)'=l+m'=l+(m+1)$.

$\sigma$. If the theorem is true for a number $n$, then there follows also $\bigl((l+m)+n\bigr)'=\bigl(l+(m+n)\bigr)'$, i.e., by [(135, III)](#equ-par-135-III)

$$
(l+m)+n'=l+(m+n)'=l+(m+n'),
$$

therefore the theorem is also true for the following number $n'$, which was to be proved.

[**142.**]{#par-142} Theorem. $m+n>m$.

Proof by complete induction [(80)](2_06_simply-infinite-systems.qmd#par-80). For

$\rho$. by [(135, II)](#equ-par-135-II) and [(91)](2_07_greater-and-less-numbers.qmd#par-91) the theorem is true for $n = 1$.

$\sigma$. If the theorem is true for a number $n$, then by [(95)](2_07_greater-and-less-numbers.qmd#par-95) it is also true for the following number $n'$, because by [(135, III)](#equ-par-135-III) and [(91)](2_07_greater-and-less-numbers.qmd#par-91)

$$
m+n'=(m+n)'>m+n,
$$

which was to be proved.

[**143.**]{#par-143} Theorem. The conditions $m>a$ and $m+n>a+n$ are equivalent.

Proof by complete induction [(80)](2_06_simply-infinite-systems.qmd#par-80). For

$\rho$. by [(135, II)](#equ-par-135-II) and [(94)](2_07_greater-and-less-numbers.qmd#par-94) the theorem is true for $n = 1$.

$\sigma$. If the theorem is true for a number $n$, then is it also true for the following number $n'$, since by [(94)](2_07_greater-and-less-numbers.qmd#par-94) the condition $m+n>a+n$ is equivalent to $(m+n)'> (a+n)'$, hence by [(135, III)](#equ-par-135-III) also equivalent to

$$
m+n'> a+n',
$$

which was to be proved.

[**144.**]{#par-144} Theorem. If $m>a$ and $n>b$, then is also

$$
m+n>a+b.
$$

::: {.proof}
For from our hypotheses we have by [(143)](#par-143) $m+n>a+n$ and $n+a>b+a$ or, what by [(140)](#par-140) is the same, $a+n>a+b$, whence the theorem follows by [(95)](2_07_greater-and-less-numbers.qmd#par-95).
:::

[**145.**]{#par-145} Theorem. If $m+n=a+n$ then $m=a$.

::: {.proof}
For if $m$ does not $=a$, hence by [(90)](2_07_greater-and-less-numbers.qmd#par-90) either $m>a$ or $m<a$, then by [(143)](#par-143) respectively $m+n>a+n$ or $m+n<a+n$, therefore by [(90)](2_07_greater-and-less-numbers.qmd#par-90) we surely cannot have $m+n=a+n$ which was to be proved.
:::

[**146.**]{#par-146} Theorem. If $l>n$, then there exists one and by [(157)](2_13_involution-of-numbers.qmd#par-157) only one number $m$ which satisfies the condition $m+n=l$.

Proof by complete induction [(80)](2_06_simply-infinite-systems.qmd#par-80). For

$\rho$. the theorem is true for $n = 1$. In fact, if $l>1$, i.e., [(89)](2_07_greater-and-less-numbers.qmd#par-89) if $l$ is contained in $N'$, and hence is the transform $m'$ of a number $m$, then by [(135, II)](#equ-par-135-II) it follows that $l=m+1$, which was to be proved.

$\sigma$. If the theorem is true for a number $n$, then we show that it is also true for the following number $n'$. In fact, if $l>n'$, then by [(91)](2_07_greater-and-less-numbers.qmd#par-91), [(95)](2_07_greater-and-less-numbers.qmd#par-95) also $l>n$, and hence there exists a number $k$ which satisfies the condition $l=k+n$; since by [(138)](#par-138) this is different from 1 (otherwise $l$ would be $=n'$) then by [(78)](2_06_simply-infinite-systems.qmd#par-78) is it the transform $m'$ of a number $m$, consequently $l=m'+n$, therefore also by [(136)](#par-136) $l=m+n'$, which was to be proved.

[^fn-1-chap-18]: The above definition of addition based immediately upon theorem  [(126)](2_09_definition-of-a-transformation-of-the-number-series-by-induction.qmd#par-126) seems to me to be the simplest. By the aid of the notion developed in [(131)](2_09_definition-of-a-transformation-of-the-number-series-by-induction.qmd#par-131) we can, however, define the sum $m+n$ by $\phi^n(m)$ or also by $\phi^m(n)$, where $\phi$ has again the foregoing meaning. In order to show the complete agreement of these definitions with the foregoing, we need by [(126)](2_09_definition-of-a-transformation-of-the-number-series-by-induction.qmd#par-126) only to show that if $\phi^n(m)$ or $\phi^m(n)$ is denoted by $\psi(n)$, the conditions $\psi(1)=m'$, $\psi(n')=\phi\psi(n)$ are fulfilled which is easily done with the aid of complete induction [(80)](2_06_simply-infinite-systems.qmd#par-80) by the help of [(131)](2_09_definition-of-a-transformation-of-the-number-series-by-induction.qmd#par-131).