project:
  type: book
  output-dir: _book

book:
  title: Essays on the theory of numbers
  author: Richard Dedekind
  date: 1901-01-01
  date-format: "YYYY"
  downloads: [pdf]
  chapters:
    - index.qmd
    - transcribers-notes.qmd  
    - part: 1_00_continuity-and-irrational-numbers.qmd
      chapters:
        - 1_01_properties-of-rational-numbers.qmd
        - 1_02_comparison-with-points-of-a-straight-line.qmd
        - 1_03_continuity-of-the-straight-line.qmd
        - 1_04_creation-of-irrational-numbers.qmd
        - 1_05_continuity-of-the-domain-of-real-numbers.qmd
        - 1_06_operations-with-real-numbers.qmd
        - 1_07_infinitesimal-analysis.qmd
    - part: 2_00_the-nature-and-meaning-of-numbers.qmd
      chapters:
        - 2_01_systems-of-elements.qmd
        - 2_02_transformation-of-a-system.qmd
        - 2_03_similarity-of-a-transformation.qmd
        - 2_04_transformation-of-a-system-in-itself.qmd
        - 2_05_the-finite-and-infinite.qmd
        - 2_06_simply-infinite-systems.qmd
        - 2_07_greater-and-less-numbers.qmd
        - 2_08_finite-and-infinite-parts.qmd
        - 2_09_definition-by-induction.qmd
        - 2_10_the-class-of-simply-infinite-systems.qmd
        - 2_11_addition-of-numbers.qmd
        - 2_12_multiplication-of-numbers.qmd
        - 2_13_involution-of-numbers.qmd
        - 2_14_number-of-elements-of-a-finite-system.qmd
    - _license.qmd
    - references.qmd

format:
  html:
    # format options
    theme:
      - cosmo
      - scss/custom.scss
    html-math-method: mathjax
    # includes
    include-in-header: 
      - file: partials/html/header.html
  pdf:
    # format options
    pdf-engine: xelatex
    # table of contents
    toc-depth: 1
    # fonts
    fontsize: 12pt
    # colors
    linkcolor: blue
    citecolor: blue
    urlcolor: blue
    colorlinks: true
    # layout
    documentclass: scrbook
    # references
    link-citations: true
    link-bibliography: true
    # includes
    include-in-header: 
      - file: partials/latex/header.tex

# language: 
lang: en
language: 
  crossref-ch-prefix: "Section"

# cross references
crossref:
  # https://quarto.org/docs/reference/metadata/crossref.html
  # not working
  # https://github.com/orgs/quarto-dev/discussions/14738#discussioncomment-17828315
  sec-labels: roman

# citations
bibliography: references/essays-on-the-theory-of-numbers.bib
csl: references/ieee.csl